Automate docker install

diff --git a/.github/workflows/dockerbuild.yml b/.github/workflows/dockerbuild.yml
--- a/.github/workflows/dockerbuild.yml
+++ b/.github/workflows/dockerbuild.yml
@@ -44,13 +44,11 @@ jobs:
     - name: Setup docker, docker-compose, and colima (missing on MacOS)
       if: runner.os == 'macos'
       run: |
-        brew install docker docker-compose colima
-        
-        # Link the Docker Compose v2 plugin so it's understood by the docker CLI
-        mkdir -p ~/.docker/cli-plugins
-        ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
-        
-        colima start
+        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+        open -a /Applications/Docker.app --args --unattended --accept-license
+        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
     - name: try doing docker build
       shell: bash -l {0}
